# https://taskfile.dev

version: '3'

vars:
  PROJECT: termo-service

tasks:
  default:
    cmds:
      - direnv exec . mamba run --live-stream -n termo-service python -m 'termo_service.cli' {{.CLI_ARGS}}
    silent: true

  logs:
    desc: logs
    cmds:
      - pm2 logs {{.PROJECT}} 

  export:
    desc: export env
    cmds:
      - direnv exec . mamba env export --no-builds -n {{.PROJECT}} > environment.yml

  start:
    desc: start
    cmds:
      - pm2 restart {{.PROJECT}} 

  stop:
    desc: stop
    cmds:
      - pm2 stop {{.PROJECT}} 

  push:
    desc: commit and pushes current changes
    cmds:
      - git add .  || true
      - gcom || true
      - git push || true